server:
  port: 5000
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
logging:
  file:
    name: D:\kiet.nguyen-dang\chuyen-de-cong-nghe-final\logs\elk-stack.log
sentry:
  dsn: https://ccfea2a997c344e29767df9f3d88d7e2@o4504211653853184.ingest.sentry.io/4504211659292672
  logging:
    minimum-breadcrumb-level: debug
    minimum-event-level: info
  in-app-includes: com.example.informationthematicbackend
  send-default-pii: true
  exception-resolver-order: -1
  traces-sample-rate: 1.0